
import java.util.*;
import java.util.concurrent.ExecutionException;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ceyda
 */
public class MovieRatingFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovieRatingFrame.class.getName());
    private static final int ROWS             = 5;
    private static final int RANDOM_POOL_SIZE = 10;

    private final DataLoader           dataLoader;
    private final RecommendationEngine engine;
    // ---- Design sekmesinde göreceğin bileşenler ----
    private final JComboBox[] cmbMovies;
    private final JTextField[] txtRatings;
    
    private final Map<String, String> moviePool = new LinkedHashMap<>();

   
    public MovieRatingFrame(DataLoader dataLoader, RecommendationEngine engine) {
        initComponents();
        this.dataLoader = dataLoader;
        this.engine     = engine;
        
        cmbMovies = new javax.swing.JComboBox[] {jComboBox1,jComboBox2,jComboBox3,jComboBox4,jComboBox5};
        txtRatings = new javax.swing.JTextField[] {jTextField1,jTextField2,jTextField3,jTextField4,jTextField5};

        
        loadRandomMovies();   // combo box'ları 10 rastgele filmle doldur
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        lblX = new javax.swing.JLabel();
        txtX = new javax.swing.JTextField();
        lblK = new javax.swing.JLabel();
        txtK = new javax.swing.JTextField();
        btnGetRecs = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResults = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Screen B — Recommendation Based on Movie Rating");
        setBackground(new java.awt.Color(245, 248, 255));

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jComboBox2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel1.setText("Movie Name:");

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addActionListener(this::jTextField4ActionPerformed);

        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(this::jTextField5ActionPerformed);

        lblX.setText("X (similar users):");

        lblK.setText("K (movie/user):");

        txtK.addActionListener(this::txtKActionPerformed);

        btnGetRecs.setBackground(new java.awt.Color(45, 140, 70));
        btnGetRecs.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnGetRecs.setForeground(new java.awt.Color(255, 255, 255));
        btnGetRecs.setText("Get Recommendation");
        btnGetRecs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGetRecs.addActionListener(this::btnGetRecsActionPerformed);

        txtResults.setEditable(false);
        txtResults.setBackground(new java.awt.Color(255, 255, 255));
        txtResults.setColumns(20);
        txtResults.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtResults.setLineWrap(true);
        txtResults.setRows(5);
        txtResults.setWrapStyleWord(true);
        txtResults.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(txtResults);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel4.setText("Rate (1-5)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblX)
                        .addGap(18, 18, 18)
                        .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblK)
                        .addGap(18, 18, 18)
                        .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGetRecs))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblX)
                    .addComponent(txtX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblK)
                    .addComponent(txtK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetRecs))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void txtKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKActionPerformed

    private void btnGetRecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetRecsActionPerformed
        
        // Kullanıcı vektörü 
        Map<String, Double> vec = new LinkedHashMap<>();
        for (String id : dataLoader.getMovieColumnIds()) vec.put(id, 0.0);

        Set<String> selected = new LinkedHashSet<>();

        for (int i = 0; i < ROWS; i++) {
            String title = (String) cmbMovies[i].getSelectedItem();
            if (title == null) { warn("Line" + (i+1) + ": no  movie selected"); return; }
            if (selected.contains(title)) {
                warn("Line " + (i+1) + ": the same movie has already been selected, choose a different one.");
                return;
            }
            int rating;
            try {
                rating = Integer.parseInt(txtRatings[i].getText().trim());
                if (rating < 1 || rating > 5) throw new NumberFormatException();
            } catch (NumberFormatException ex) {
                warn("Line " + (i+1) + ": the score must be an integer between 1 and 5.");
                return;
            }
            selected.add(title);
            String id = moviePool.get(title);
            if (id != null) vec.put(id, (double) rating);
        }

        int X, K;
        try {
            X = Integer.parseInt(txtX.getText().trim());
            K = Integer.parseInt(txtK.getText().trim());
            if (X <= 0 || K <= 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            warn("X and K must be positive integers.");
            return;
        }

        txtResults.setText("Calculating...");
        btnGetRecs.setEnabled(false);
        txtResults.setText("Wait a moment...");

        final Map<String, Double> fVec = vec;
        final int fX = X, fK = K;
        new SwingWorker<List<String>, Void>() {
            @Override protected List<String> doInBackground() {
                return engine.recommendByRatings(fVec, fX, fK);
            }
            @Override protected void done() {
                try { showResults(fX, fK, get()); }
                catch (InterruptedException | ExecutionException ex) { txtResults.setText("Error: " + ex.getMessage()); }
            }
        }.execute();
        btnGetRecs.setEnabled(true);

    }//GEN-LAST:event_btnGetRecsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    // Tüm filmlerden 10 tanesini rastgele seçim
    public void loadRandomMovies() {
        moviePool.clear();

        List<Map.Entry<String, String>> entries =
                new ArrayList<>(dataLoader.getMovieNames().entrySet()); // id → title
        Collections.shuffle(entries);

        int take = Math.min(RANDOM_POOL_SIZE, entries.size());
        for (int i = 0; i < take; i++)
            moviePool.put(entries.get(i).getValue(), entries.get(i).getKey()); // title → id

        List<String> titles = new ArrayList<>(moviePool.keySet());

        for (int i = 0; i < ROWS; i++) {
            cmbMovies[i].removeAllItems();
            for (String t : titles) cmbMovies[i].addItem(t);
            if (i < titles.size()) cmbMovies[i].setSelectedIndex(i);
            txtRatings[i].setText("");
        }
    }

    

    private void showResults(int X, int K, List<String> recs) {
        StringBuilder sb = new StringBuilder();
        sb.append("X = ").append(X).append("  |  K = ").append(K)
          .append("  |  Total recommendation:").append(recs.size()).append("\n");
        sb.append("─".repeat(55)).append("\n\n");

        if (recs.isEmpty()) {
            sb.append("No recommendation found.");
        } else {
            for (int i = 0; i < recs.size(); i++) {
                if (i % K == 0)
                    sb.append("[ Similar User #").append(i / K + 1)
                      .append(" — Highest ").append(K).append(" Movie ]\n");
                sb.append("  ").append(i % K + 1).append(". ").append(recs.get(i)).append("\n");
                if (i % K == K - 1) sb.append("\n");
            }
        }
        txtResults.setText(sb.toString());
        txtResults.setCaretPosition(0);
    }

    private void warn(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Warning", JOptionPane.WARNING_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetRecs;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblK;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextField txtK;
    private javax.swing.JTextArea txtResults;
    private javax.swing.JTextField txtX;
    // End of variables declaration//GEN-END:variables
}
